// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Data.Data;

#nullable disable

namespace Projekt.Data.Migrations
{
    [DbContext(typeof(ProjektContext))]
    [Migration("20220504215749_m8")]
    partial class m8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Projekt.Data.Data.CMS.CzymSieZajmujemy", b =>
                {
                    b.Property<int>("IdCzymSieZajmujemy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCzymSieZajmujemy"), 1L, 1);

                    b.Property<string>("LinkCzymSieZajmujemy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pozycja")
                        .HasColumnType("int");

                    b.Property<string>("Tresc1CzymSieZajmujemy")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Tresc2CzymSieZajmujemy")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TytulCzymSieZajmujemy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCzymSieZajmujemy");

                    b.ToTable("CzymSieZajmujemy");
                });

            modelBuilder.Entity("Projekt.Data.Data.CMS.Kontakt", b =>
                {
                    b.Property<int>("IdKontaktu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKontaktu"), 1L, 1);

                    b.Property<int>("Pozycja")
                        .HasColumnType("int");

                    b.Property<string>("TrescKontaktu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKontaktu");

                    b.ToTable("Kontakt");
                });

            modelBuilder.Entity("Projekt.Data.Data.CMS.Nawigacja", b =>
                {
                    b.Property<int>("IdNawigacji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNawigacji"), 1L, 1);

                    b.Property<string>("LinkNawigacji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pozycja")
                        .HasColumnType("int");

                    b.Property<string>("TrescNawigacji")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TytulNawigacji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNawigacji");

                    b.ToTable("Nawigacja");
                });

            modelBuilder.Entity("Projekt.Data.Data.CMS.Opinie", b =>
                {
                    b.Property<int>("IdOpini")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOpini"), 1L, 1);

                    b.Property<string>("ImieINazwiskoDodajacego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkOpini")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pozycja")
                        .HasColumnType("int");

                    b.Property<string>("TrescOpini")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("IdOpini");

                    b.ToTable("Opinie");
                });

            modelBuilder.Entity("Projekt.Data.Data.CMS.PytaniaIOdpowiedzi", b =>
                {
                    b.Property<int>("IdPytaniaIOdpowiedzi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPytaniaIOdpowiedzi"), 1L, 1);

                    b.Property<string>("LinkPytaniaIOdpowiedzi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pozycja")
                        .HasColumnType("int");

                    b.Property<string>("TrescPytaniaIOdpowiedzi")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TytulPytaniaIOdpowiedzi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPytaniaIOdpowiedzi");

                    b.ToTable("PytaniaIOdpowiedzi");
                });
#pragma warning restore 612, 618
        }
    }
}
